km = float(input("Enter distance in km : "))
print("Distance in km : ",km)
print("Distance in m : ", km*1000)
print("Distance in feet : ", round(km*3280.84 , 2))
print("Distance in inches : ", round(km*39370.1 , 2))
print("Distance in cm : ", round(km*100000, 2))